// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.28.2
// source: registrations_model.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ResponseDefault struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Error   string `protobuf:"bytes,1,opt,name=error,proto3" json:"error"`
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message"`
}

func (x *ResponseDefault) Reset() {
	*x = ResponseDefault{}
	if protoimpl.UnsafeEnabled {
		mi := &file_registrations_model_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResponseDefault) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseDefault) ProtoMessage() {}

func (x *ResponseDefault) ProtoReflect() protoreflect.Message {
	mi := &file_registrations_model_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseDefault.ProtoReflect.Descriptor instead.
func (*ResponseDefault) Descriptor() ([]byte, []int) {
	return file_registrations_model_proto_rawDescGZIP(), []int{0}
}

func (x *ResponseDefault) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *ResponseDefault) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_registrations_model_proto protoreflect.FileDescriptor

var file_registrations_model_proto_rawDesc = []byte{
	0x0a, 0x19, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x5f,
	0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x6d, 0x69, 0x63,
	0x72, 0x6f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74,
	0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x41, 0x0a,
	0x0f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x42, 0x3a, 0x5a, 0x38, 0x62, 0x69, 0x74, 0x62, 0x75, 0x63, 0x6b, 0x65, 0x74, 0x2e, 0x6f, 0x72,
	0x67, 0x2f, 0x65, 0x75, 0x63, 0x61, 0x74, 0x75, 0x72, 0x2f, 0x6d, 0x69, 0x63, 0x72, 0x6f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2d, 0x72, 0x65, 0x67, 0x69, 0x73, 0x74, 0x72, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x67, 0x72, 0x70, 0x63, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_registrations_model_proto_rawDescOnce sync.Once
	file_registrations_model_proto_rawDescData = file_registrations_model_proto_rawDesc
)

func file_registrations_model_proto_rawDescGZIP() []byte {
	file_registrations_model_proto_rawDescOnce.Do(func() {
		file_registrations_model_proto_rawDescData = protoimpl.X.CompressGZIP(file_registrations_model_proto_rawDescData)
	})
	return file_registrations_model_proto_rawDescData
}

var file_registrations_model_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_registrations_model_proto_goTypes = []interface{}{
	(*ResponseDefault)(nil), // 0: microservice.registrations.model.ResponseDefault
}
var file_registrations_model_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_registrations_model_proto_init() }
func file_registrations_model_proto_init() {
	if File_registrations_model_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_registrations_model_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ResponseDefault); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_registrations_model_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_registrations_model_proto_goTypes,
		DependencyIndexes: file_registrations_model_proto_depIdxs,
		MessageInfos:      file_registrations_model_proto_msgTypes,
	}.Build()
	File_registrations_model_proto = out.File
	file_registrations_model_proto_rawDesc = nil
	file_registrations_model_proto_goTypes = nil
	file_registrations_model_proto_depIdxs = nil
}
